### ISSUE TITLE
Maxi3dx+ having no music as well as crashing when selecting a car brand and when crown ghost cars show up on attract mode

### ISSUE THREAD

**Issue by FriedPotatoes49** [BroGamer4256/WanganArcadeLoader0.5#10]
It seems like the same issue that happened on versions 0.1.2 and below for me are happening on 0.2 and above after i got a JP dump. I tried to check the test mode for if the audio had something to do with that but all the settings seem to be fine. Sound effects seem to work just fine which is the weirdest part. I'll leave logs for both crashes here:
[crownghostcrash.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14547719/crownghostcrash.txt)
[carselectioncrashlog.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14547720/carselectioncrashlog.txt)

**Comment by BroGamer4256** [comment]
Can you please run the `locale` command and post the result

**Comment by FriedPotatoes49** [comment]
[locale.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14547813/locale.txt)

**Comment by BroGamer4256** [comment]
Please try the [latest build](https://github.com/BroGamer4256/WanganArcadeLoader0.5/actions/runs/8217172127)

**Comment by FriedPotatoes49** [comment]
It works!
