### ISSUE TITLE
Suggest that version information is looked up from available strings rather than hash

### ISSUE THREAD

**Issue by winteriscomingpinball** [BroGamer4256/WanganArcadeLoader0.5#11]
https://github.com/BroGamer4256/WanganArcadeLoader0.5/blob/6f733c31b959878b90bb39e4248143d472caf563/src/lib.rs#L440

Looking up version by hash is not as reliable as looking up from known text in the executable.  There are at least 2 releases of 3DX+ (ver A16 and B02), and hash of the B02 version I have does not match what is in the launcher.

You can parse strings starting at named address: gRomInfo
Possible strings there are:
PROJECT V386
PROJECT V363
PROJECT V337

V386=3DX+
V363=3DX
V337=3

The immediate next string has release info.
Possible strings are:
G4-RELEASE
G4-RELEASE_US
G4-RELEASE_CN (only assuming here as I have not analyzed a CN version)

Nothing after RELEASE=Japanese
US=Export/US
CN=Chinese (assuming value for this one)

**Comment by BroGamer4256** [comment]
This should be fixed in the latest commit
