### ISSUE TITLE
how to play wmmt 3dx+ without teknoparrot

### ISSUE THREAD

**Issue by n11ku** [BroGamer4256/WanganArcadeLoader0.5#12]
excuse me admin,how to play wmmt 3dx+ in steam deck steam os linux ver?,or can play i  dualboot windows 10 without teknoparrot?,or must use start.sh to play,how to do that?,because i'm new in linux os,so in linux can use yacardemu to play ghost mode?,thank you

**Comment by BroGamer4256** [comment]
I cannot understand a single thing you're trying to say. You need to be on linux to play 3, 3DX, or 3DX+ with WAL. You achieve this by copying the release files into your game folder and simply running start.sh. This loader does not work with yacardemu and instead has its own card emulator built in.

**Comment by n11ku** [comment]
ok thank you
