### ISSUE TITLE
Weird errors when attempting to run start.sh.

### ISSUE THREAD

**Issue by BionicSeaSerpent** [BroGamer4256/WanganArcadeLoader0.5#13]
running start.sh results in the following errors:
`ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
env: './main': No such file or directory
`
if of any relevance, i have to enter the terminal and manually start with `bash start.sh`

**Comment by BroGamer4256** [comment]
The loader needs to be in the same folder as WMMT 3, 3DX, or 3DX+

**Comment by BionicSeaSerpent** [comment]
moving the files into the data folder results in the same errors and creates more of them.
`cp: cannot stat './data/sound/bgm/maxi3/sys_04.wav': No such file or directory
touch: cannot touch './data/shader/.recompiled': No such file or directory
(0) : fatal error C9999: Can't open file: ./data/shader/*.cg
(0) : fatal error C9999: Can't open file: ./data/shader/*.cg
ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libwal_3dxp.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
env: './main': No such file or directory`

**Comment by BroGamer4256** [comment]
Not the data directory of the game files, just the games folder that contains the `main` file

**Comment by BionicSeaSerpent** [comment]
got it running, cheers
