### ISSUE TITLE
It almost works

### ISSUE THREAD

**Issue by hjri** [BroGamer4256/WanganArcadeLoader0.5#5]
But it seems that it crashes somewhere around trying to load MESA drivers
[log.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14312956/log.txt)

**Comment by leezhiwei** [comment]
IDK if this helps, https://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by unless we can load 2 libstdc++.so

**Comment by BroGamer4256** [comment]
This should be fixed by the latest release, 0.2
