### ISSUE TITLE
Error while loading shared libraries: librt.so.1: file too short

### ISSUE THREAD

**Issue by FriedPotatoes49** [BroGamer4256/WanganArcadeLoader0.5#8]
It seems like version 0.2 and beyond have this same issue. When I run start.sh it first says permission denied for main.elf, so I marked main as executable, then after marking it as executable, I get the error: "Error while loading shared libraries: librt.so.1: file too short". This weirdly never happens on versions below 0.2, including marking main as executable. The game does run but without music and crashes when selecting a car brand and when the crown ghosts show on the attract mode. I'll leave 2 logs for 0.2 and beyond and 0.1.2 
[log_0.2.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14543993/log_0.2.txt)
[log_0.1.2.txt](https://github.com/BroGamer4256/WanganArcadeLoader0.5/files/14543994/log_0.1.2.txt)

**Comment by BroGamer4256** [comment]
That's a dump issue, the so's aren't properly linked.

**Comment by FriedPotatoes49** [comment]
Makes sense, since I have the chinese bootleg dump.  I'll find a JP dump then.
